import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <section>
        <p>Start About</p>
        {children}
        <p>End About.</p>
      </section>
  );
}
