"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useRouter } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const router = useRouter();




  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar-1">
          <button onClick={() => router.push("/")}>Bosh Sahifa</button>
          <button onClick={() =>router.push("/about")}>Men Haqimda</button>
          <button onClick={() => router.push("/contact")}>Bog'lanish</button>
        </div>
        {/* <div className="navbar">
          <div>
            <Link href={"/"}>Bosh sahifa</Link>
          </div>
          <div>
            <Link href={"/about"}>Men haqimda </Link>
          </div>
          <div>
            <Link href={"/contact"}>Bog'lanish</Link>
          </div>
        </div> */}
        {children}
      </body>
    </html>
  );
}
