import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar-1">
          <button>Bosh Sahifa</button>
          <button>Men Haqimda</button>
          <button>Bog'lanish</button>
        </div>
        {/* <div className="navbar">
          <div>
            <Link href={"/"}>Bosh sahifa</Link>
          </div>
          <div>
            <Link href={"/about"}>Men haqimda </Link>
          </div>
          <div>
            <Link href={"/contact"}>Bog'lanish</Link>
          </div>
        </div> */}
        {children}
      </body>
    </html>
  );
}
